release

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
-# cat $1/Procfile
-echo <<EOF
----
-default_process_types:
-   web: sh start-process.sh bin/heroku-hello-world
-EOF
+if [ ! -f $1/Procfile ]; then
+    echo "Error: release couldnt find Procfile"
+    exit 1
+fi
+
+cat $1/Procfile
